import type { Theme } from './types'

export const classicThemes: Theme[] = [
  {
    id: 'classic-minimal',
    name: 'Classic Minimal',
    description: 'Clean minimal typographic style',
    group: 'classic',
    styles: {
      container: 'font-family: Georgia, "Times New Roman", Times, serif; font-size: 17px; line-height: 1.8; color: #222222; background: #ffffff; padding: 48px 64px; max-width: 800px; margin: 0 auto;',
      h1: 'font-size: 30px; font-weight: 700; color: #111111; margin: 36px 0 18px; letter-spacing: -0.5px;',
      h2: 'font-size: 24px; font-weight: 700; color: #111111; margin: 30px 0 14px; letter-spacing: -0.3px;',
      h3: 'font-size: 19px; font-weight: 600; color: #222222; margin: 24px 0 10px;',
      p: 'margin: 14px 0; color: #333333; line-height: 1.8;',
      a: 'color: #0066cc; text-decoration: underline;',
      'pre.hljs': 'background: #f6f6f6; border: 1px solid #e0e0e0; border-radius: 4px; padding: 16px; overflow-x: auto; margin: 16px 0;',
      code: 'background: #f6f6f6; border: 1px solid #e0e0e0; border-radius: 3px; padding: 2px 5px; font-family: "Courier New", Courier, monospace; font-size: 14px;',
      blockquote: 'border-left: 3px solid #999999; margin: 20px 0; padding: 10px 20px; color: #666666; font-style: italic;',
      ul: 'margin: 14px 0; padding-left: 28px;',
      ol: 'margin: 14px 0; padding-left: 28px;',
      li: 'margin: 8px 0;',
      table: 'border-collapse: collapse; width: 100%; margin: 16px 0;',
      th: 'border: 1px solid #cccccc; padding: 10px 14px; text-align: left; background: #f6f6f6; font-weight: 700;',
      td: 'border: 1px solid #cccccc; padding: 10px 14px;',
      img: 'max-width: 100%; margin: 20px 0;',
      hr: 'border: none; border-top: 1px solid #cccccc; margin: 28px 0;',
    },
  },
  {
    id: 'classic-academic',
    name: 'Classic Academic',
    description: 'Academic paper style with serif fonts',
    group: 'classic',
    styles: {
      container: 'font-family: "Palatino Linotype", Palatino, "Book Antiqua", Georgia, serif; font-size: 16px; line-height: 1.9; color: #1a1a1a; background: #fffef9; padding: 56px 72px; max-width: 780px; margin: 0 auto;',
      h1: 'font-size: 26px; font-weight: 700; color: #1a1a1a; margin: 40px 0 16px; text-align: center; letter-spacing: 0.5px;',
      h2: 'font-size: 20px; font-weight: 700; color: #1a1a1a; margin: 32px 0 12px; border-bottom: 1px solid #cccccc; padding-bottom: 4px;',
      h3: 'font-size: 17px; font-weight: 600; color: #1a1a1a; margin: 24px 0 8px; font-style: italic;',
      p: 'margin: 12px 0; color: #1a1a1a; line-height: 1.9; text-align: justify;',
      a: 'color: #003399; text-decoration: underline;',
      'pre.hljs': 'background: #f8f8f0; border: 1px solid #d0d0c0; padding: 14px; overflow-x: auto; margin: 16px 0; font-size: 13px;',
      code: 'background: #f8f8f0; border: 1px solid #d0d0c0; padding: 1px 4px; font-family: "Courier New", Courier, monospace; font-size: 13px;',
      blockquote: 'border-left: 2px solid #888888; margin: 20px 0; padding: 8px 20px; color: #555555; font-style: italic;',
      ul: 'margin: 12px 0; padding-left: 28px;',
      ol: 'margin: 12px 0; padding-left: 28px;',
      li: 'margin: 6px 0;',
      table: 'border-collapse: collapse; width: 100%; margin: 20px 0;',
      th: 'border: 1px solid #aaaaaa; padding: 8px 12px; text-align: left; background: #f0ede0; font-weight: 700;',
      td: 'border: 1px solid #aaaaaa; padding: 8px 12px;',
      img: 'max-width: 100%; margin: 20px auto; display: block;',
      hr: 'border: none; border-top: 1px solid #aaaaaa; margin: 32px 0;',
    },
  },
  {
    id: 'classic-newsletter',
    name: 'Classic Newsletter',
    description: 'Newsletter layout with clear hierarchy',
    group: 'classic',
    styles: {
      container: 'font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif; font-size: 15px; line-height: 1.7; color: #333333; background: #ffffff; padding: 40px 50px; max-width: 680px; margin: 0 auto;',
      h1: 'font-size: 32px; font-weight: 800; color: #111111; margin: 0 0 24px; line-height: 1.3;',
      h2: 'font-size: 20px; font-weight: 700; color: #111111; margin: 28px 0 10px; padding-top: 16px; border-top: 3px solid #111111;',
      h3: 'font-size: 16px; font-weight: 700; color: #333333; margin: 20px 0 8px; text-transform: uppercase; letter-spacing: 0.5px;',
      p: 'margin: 10px 0; color: #333333; line-height: 1.7;',
      a: 'color: #e53e3e; text-decoration: underline; font-weight: 600;',
      'pre.hljs': 'background: #f4f4f4; border-left: 4px solid #333333; padding: 14px; overflow-x: auto; margin: 16px 0;',
      code: 'background: #f4f4f4; padding: 2px 5px; font-family: "Courier New", Courier, monospace; font-size: 13px; color: #e53e3e;',
      blockquote: 'border-left: 4px solid #e53e3e; margin: 20px 0; padding: 8px 16px; color: #555555; background: #fff5f5;',
      ul: 'margin: 10px 0; padding-left: 24px;',
      ol: 'margin: 10px 0; padding-left: 24px;',
      li: 'margin: 6px 0;',
      table: 'border-collapse: collapse; width: 100%; margin: 16px 0;',
      th: 'background: #111111; color: #ffffff; padding: 10px 14px; text-align: left; font-weight: 700;',
      td: 'border-bottom: 1px solid #e0e0e0; padding: 10px 14px;',
      img: 'max-width: 100%; margin: 16px 0;',
      hr: 'border: none; border-top: 3px solid #111111; margin: 28px 0;',
    },
  },
]
